apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-x5pr
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-rxpp-tenant/rhtap-demo-app/hacbs-test-project-x5pr@sha256:cb4612f21a5ee88101b21988431a9dd3ca0993b94cc0b60195b7efe4cddd0806
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
